include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    invariant_booleans: true
    no_adjacent_strings_in_list: true
    throw_in_finally: true
    unnecessary_statements: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_returning_null: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cast_nullable_to_non_nullable: true
    directives_ordering: true
    eol_at_end_of_file: true
    leading_newlines_in_multiline_strings: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    depend_on_referenced_packages: true
